baseURL = 'https://reanimate.school'
title = 'Summer School ReAnimate'

theme = 'hugo.386'

# defaultContentLanguage = 'en'
# defaultContentLanguageInSubdir = true
# languageCode = 'en-us'
# [languages]
#   [languages.en]
#     contentDir = 'content/en'
#     disabled = false
#     languageCode = 'en-US'
#     languageDirection = 'ltr'
#     languageName = 'English'
#     # title = 'Project Documentation'
#     weight = 2
#     [languages.en.params]
#       color = 'blue'
#   [languages.fr]
#     languageCode = 'fr'
#     title = 'Min blogg'

preserveTaxonomyNames = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[params]
    # The name to display as main title in the home page
    mainpagetitle = "Summer School ReAnimate"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "2024 Summer School on Retro Gaming History, Critic, and Development" 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "A summer school dedicated to retro gaming, which invites both humanities and engineering to provide unique insights on retro gaming, both theoretical and practical, and opportunities for cross-fertilization among research fields. Supported by the ACM SIGSOFT and Cloanto."

    # The name to display in the copyright section in the footer
    copyrightname = "Summer School ReAnimate"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = ""

    # Show the "built on Hugo" disclaimer
    showhugo = true

    # Urls for social networks
    # facebook = "https://facebook.com"
    # twitter = "https://twitter.com"
    # linkedin = "https://linkedin.com"
    # github = "https://github.com"
    # gitlab = "https://gitlab.com"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = ""

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = ""

    # Text to go before copyright information
    prefix = ""

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = ""

[params.meta]
    favicon = true

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "organisers" 
    name = "Organisers"       
    url = "/organisers/"      
    weight = 10   

  [[menu.main]]
    identifier = "objectives"
    name = "Objectives"
    url = "/objectives/"
    weight = 10

  [[menu.main]]
    identifier = "speakers"
    name = "Speakers"
    url = "/speakers/"
    weight = 10

  [[menu.main]]
    identifier = "sponsors"
    name = "Sponsors"
    url = "/sponsors/"
    weight = 10

  [[menu.main]]
    identifier = "program"
    name = "Program"
    url = "/program/"
    weight = 20

  [[menu.main]]
    identifier = "registration"
    name = "Registration"
    url = "/registration/"
    weight = 30

  [[menu.main]]
    identifier = "contact" 
    name = "Contact"       
    url = "/contact/"      
    weight = 40        

  # [[menu.main]]
  #   identifier = "news"
  #   name = "News"
  #   url = "/news/"       # The path can lead to a content folder too.
  #   weight = 20

[taxonomies]
    tag = "tags"
    # category = "categories"   
    # disableKinds = ['taxonomy', 'term']


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

